import Foundation

/// Drops the two artifacts that let agents running INSIDE terminals talk to the task board:
///  • `~/.tfa/bin/tfa-task` — a small shell CLI that reads/writes the SQLite board (`~/.tfa/board.db`)
///    via the system `sqlite3`. Agents call it to register, claim, comment, and complete tasks.
///  • `<agent-home>/skills/tfa-task/SKILL.md` — installed for both Claude Code and Codex.
/// Both are regenerated on every launch (generated artifacts owned by TFA). Idempotent.
enum AgentTooling {
    static func install() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let binDir = home.appendingPathComponent(".tfa/bin", isDirectory: true)

        // The CLI lives under ~/.tfa (our own dir). Write only when changed.
        let cli = binDir.appendingPathComponent("tfa-task")
        if writeIfChanged(cliScript, to: cli, createDir: binDir) {
            try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: cli.path)
        }
        // Shell integration (OSC 133 marks → precise busy/idle + exit codes). The file is always
        // (re)generated; SOURCING it from ~/.zshrc is opt-in via 设置 (ShellIntegrationInstall).
        let tfaDir = home.appendingPathComponent(".tfa", isDirectory: true)
        writeIfChanged(shellIntegrationScript, to: tfaDir.appendingPathComponent("shell-integration.sh"), createDir: tfaDir)
        // Install the same portable Agent Skill for both supported agents. Writes into another
        // app's data directory can trigger macOS privacy prompts, so unchanged files are untouched.
        for platform in AgentPlatform.allCases {
            // Preserve the existing Claude behavior, but do not create a Codex home for users who
            // have never installed or run Codex.
            if platform == .codex,
               !FileManager.default.fileExists(atPath: platform.homeDirectory.path) { continue }
            let skillDir = platform.skillsDirectory.appendingPathComponent("tfa-task", isDirectory: true)
            writeIfChanged(skillDoc, to: skillDir.appendingPathComponent("SKILL.md"), createDir: skillDir)
        }
    }

    /// Write `content` to `url` only if the file is missing or differs — avoids needless writes (and,
    /// for agent data directories, the macOS privacy prompt that every write may raise). Returns whether
    /// a write happened. Creating the parent dir + reading to compare don't trip the WRITE prompt.
    @discardableResult
    private static func writeIfChanged(_ content: String, to url: URL, createDir: URL) -> Bool {
        if let existing = try? String(contentsOf: url, encoding: .utf8), existing == content { return false }
        try? FileManager.default.createDirectory(at: createDir, withIntermediateDirectories: true)
        return (try? content.write(to: url, atomically: true, encoding: .utf8)) != nil
    }

    // MARK: - the CLI (SQLite-backed)

    private static let cliScript = ##"""
#!/bin/sh
# tfa-task — read/write the TFA task board (SQLite at ~/.tfa/board.db). Auto-generated by TFA; do not edit.
# Lets an agent register itself, claim/comment/complete tasks. Set TFA_AGENT to your agent name.
set -e
DB="$HOME/.tfa/board.db"
mkdir -p "$HOME/.tfa"
command -v sqlite3 >/dev/null 2>&1 || { echo "tfa-task 需要 sqlite3（macOS 自带 /usr/bin/sqlite3）" >&2; exit 1; }

# Ensure schema + WAL (matches the app). Safe to run every time.
sqlite3 "$DB" >/dev/null 2>&1 <<'SQL'
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'todo', assignee TEXT, createdAt REAL NOT NULL DEFAULT 0, updatedAt REAL NOT NULL DEFAULT 0, ord REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, taskId TEXT NOT NULL, by TEXT NOT NULL DEFAULT 'agent', text TEXT NOT NULL DEFAULT '', at REAL NOT NULL DEFAULT 0, kind TEXT NOT NULL DEFAULT 'note');
CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL DEFAULT '', session TEXT, cwd TEXT NOT NULL DEFAULT '', external INTEGER NOT NULL DEFAULT 0, lastSeen REAL NOT NULL DEFAULT 0);
SQL
# Migrate older DBs (no-op if the column already exists).
sqlite3 "$DB" "ALTER TABLE comments ADD COLUMN kind TEXT NOT NULL DEFAULT 'note';" 2>/dev/null || true

_now() { date +%s; }
_uuid() { uuidgen | tr 'A-Z' 'a-z'; }
_who() { printf '%s' "${TFA_AGENT:-agent}"; }
# SQL-quote a value: wrap in single quotes, doubling any embedded single quote.
_q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"; }
_db() { sqlite3 -batch "$DB" "$@"; }
# resolve a short id (first 8) or prefix to the full task id
_resolve() { _db -noheader "SELECT id FROM tasks WHERE substr(id,1,8)=$(_q "$1") OR id LIKE $(_q "$1%") LIMIT 1;"; }

cmd="${1:-help}"; [ $# -gt 0 ] && shift || true
case "$cmd" in
  list)
    _db -noheader "SELECT substr(id,1,8) || '  [' || status || ']  ' || title || coalesce('  @'||assignee,'') FROM tasks ORDER BY ord;" ;;
  show)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }
    _db -noheader "SELECT '标题: '||title||char(10)||'状态: '||status||char(10)||'指派: '||coalesce(assignee,'未指派')||char(10)||char(10)||body FROM tasks WHERE id=$(_q "$id");"
    echo; echo "进展:"; _db -noheader "SELECT '· '||by||': '||text FROM comments WHERE taskId=$(_q "$id") ORDER BY at;" ;;
  add)
    [ -n "$1" ] || { echo "用法: tfa-task add <标题>" >&2; exit 1; }
    id="$(_uuid)"; t="$(_now)"
    _db "INSERT INTO tasks (id,title,body,status,assignee,createdAt,updatedAt,ord) VALUES ($(_q "$id"),$(_q "$*"),'','todo',NULL,$t,$t,-$t);"
    printf '已创建 %.8s\n' "$id" ;;
  claim)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; t="$(_now)"
    _db "UPDATE tasks SET status='doing',updatedAt=$t WHERE id=$(_q "$id");"
    echo "已开始 $1（→ 进行中）" ;;
  comment)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; shift
    t="$(_now)"; cid="$(_uuid)"
    _db "INSERT INTO comments (id,taskId,by,text,at,kind) VALUES ($(_q "$cid"),$(_q "$id"),$(_q "$(_who)"),$(_q "$*"),$t,'note'); UPDATE tasks SET updatedAt=$t WHERE id=$(_q "$id");"
    echo "已记录" ;;
  step)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; shift
    t="$(_now)"; cid="$(_uuid)"
    _db "INSERT INTO comments (id,taskId,by,text,at,kind) VALUES ($(_q "$cid"),$(_q "$id"),$(_q "$(_who)"),$(_q "$*"),$t,'step'); UPDATE tasks SET status='doing',updatedAt=$t WHERE id=$(_q "$id");"
    echo "已记录执行步骤" ;;
  ask)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; shift
    t="$(_now)"; cid="$(_uuid)"
    _db "INSERT INTO comments (id,taskId,by,text,at,kind) VALUES ($(_q "$cid"),$(_q "$id"),$(_q "$(_who)"),$(_q "$*"),$t,'question'); UPDATE tasks SET updatedAt=$t WHERE id=$(_q "$id");"
    echo "已提问，等待人回复" ;;
  done)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; t="$(_now)"
    _db "UPDATE tasks SET status='done',updatedAt=$t WHERE id=$(_q "$id");"
    echo "已完成 $1" ;;
  block)
    id="$(_resolve "$1")"; [ -n "$id" ] || { echo "未找到任务 $1" >&2; exit 1; }; shift
    t="$(_now)"; cid="$(_uuid)"
    _db "UPDATE tasks SET status='blocked',updatedAt=$t WHERE id=$(_q "$id");"
    [ -n "$*" ] && _db "INSERT INTO comments (id,taskId,by,text,at,kind) VALUES ($(_q "$cid"),$(_q "$id"),$(_q "$(_who)"),$(_q "$*"),$t,'blocked');"
    echo "已标记受阻（推进不下去）$1" ;;
  *)
    cat <<'EOF'
tfa-task — TFA 任务看板命令行（数据存 SQLite：~/.tfa/board.db）
  tfa-task list                 列出所有任务
  tfa-task show <id>            查看任务详情（id 取前 8 位即可）
  tfa-task add <标题>           新建任务
  tfa-task claim <id>          开始任务（→ 进行中）
  tfa-task step <id> <文字>     记录一步执行过程（推荐：边做边报）
  tfa-task comment <id> <文字>  记录一条普通备注
  tfa-task ask <id> <问题>      需要人回复才能继续
  tfa-task block <id> [原因]    推进不下去 / 受阻
  tfa-task done <id>           标记完成
提示：export TFA_AGENT="你的名字" 让回报带上署名。
EOF
    ;;
esac
"""##

    // MARK: - the skill

    private static let skillDoc = #"""
---
name: tfa-task
description: 用 TFA 任务看板协作。当你在 TFA 终端里收到「请处理 TFA 任务 #xxxx」这样的指派、或需要登记/认领/回报任务进度、把工作写回看板时使用。看板存在本机 SQLite（~/.tfa/board.db），用 `~/.tfa/bin/tfa-task` 命令读写。
---

# TFA 任务看板（tfa-task）

TFA 把每个任务渲染成看板卡片，可以指派给某个终端 agent 并「派发」——派发时会往该终端发一行：
`请处理 TFA 任务 #<id>：<标题>。用 ~/.tfa/bin/tfa-task show <id> 看详情，完成后 ~/.tfa/bin/tfa-task done <id>。`

看板数据在共享 SQLite 文件 `~/.tfa/board.db`，TFA 实时监视它的变化。你用 CLI 写回的任何进度，TFA 都会立刻在看板上反映。

## 命令（全部用 `~/.tfa/bin/tfa-task`）

```
~/.tfa/bin/tfa-task list                 # 所有任务
~/.tfa/bin/tfa-task show <id>            # 任务详情（id 取前 8 位）
~/.tfa/bin/tfa-task add "<标题>"          # 新建任务
~/.tfa/bin/tfa-task claim <id>           # 开始（→ 进行中）
~/.tfa/bin/tfa-task step <id> "<这一步做了啥>"  # 记录一步执行过程（边做边报）
~/.tfa/bin/tfa-task comment <id> "<备注>" # 普通备注
~/.tfa/bin/tfa-task ask <id> "<问题>"     # 需要人回复才能继续
~/.tfa/bin/tfa-task block <id> "<原因>"   # 推进不下去 / 受阻
~/.tfa/bin/tfa-task done <id>            # 标记完成
```

建议先 `export TFA_AGENT="你的名字"`，回报会带署名。任务由人在 TFA 看板上指派给某个终端；你在被指派的终端里用上面的命令回报即可。

## 标准工作流（务必边做边回报，TFA 看板会实时显示你的执行记录）

1. 被派发任务后，先 `tfa-task show <id>` 读全文。
2. `tfa-task claim <id>` 认领。
3. **每完成一步就 `tfa-task step <id> "刚做了什么 / 下一步打算"`** —— 这就是看板上的执行记录。
4. 需要人确认 / 给信息才能继续 → `tfa-task ask <id> "你的问题"`（看板会标「待回复」）。
5. 实在推进不下去 → `tfa-task block <id> "卡在哪"`（看板进「受阻」列）。
6. 全部做完，**先回报最终结果** `tfa-task step <id> "最终结果：改了哪些文件 / 验证情况"`，再 `tfa-task done <id>`。

依赖系统自带的 `sqlite3`。也可直接查库：`sqlite3 ~/.tfa/board.db "SELECT * FROM tasks;"`。
"""#

    /// OSC 133 shell-integration snippet (zsh + bash). Emits: `C` when a command starts, `D;<exit>`
    /// when it finishes, `A` at each prompt — TFA parses these from the pane stream for a PRECISE
    /// busy/idle signal and command exit codes. Harmless in other terminals (iTerm2/WezTerm use the
    /// same convention). Sourcing is opt-in (设置 → Shell 集成 appends one line to ~/.zshrc).
    private static let shellIntegrationScript = #"""
# TFA shell integration — OSC 133 marks (FinalTerm convention) so TFA knows precisely when this
# shell is at a prompt, when a command starts, and each command's exit code.
# Generated by TFA; safe to source multiple times; harmless outside TFA (iTerm2 etc. understand it).
[ -n "$__TFA_SHELL_INTEGRATION" ] && return
__TFA_SHELL_INTEGRATION=1

if [ -n "$ZSH_VERSION" ]; then
  # 7770 is TFA-private: the command line about to run (capped, newlines flattened) — TFA's
  # per-terminal「过程记录」pairs it with the next D mark. Other terminals ignore unknown OSCs.
  __tfa_preexec() { local __c="${1[1,160]}"; __c="${__c//$'\n'/ }"; printf '\033]133;C\007\033]7770;%s\007' "$__c"; }
  __tfa_precmd()  { local __ec=$?; printf '\033]133;D;%s\007\033]133;A\007' "$__ec"; }
  autoload -Uz add-zsh-hook
  add-zsh-hook preexec __tfa_preexec
  add-zsh-hook precmd  __tfa_precmd
elif [ -n "$BASH_VERSION" ]; then
  # bash has no reliable preexec without a DEBUG-trap dance — prompt marks (D + A) alone still give
  # TFA the at-prompt signal and exit codes; "running" falls back to the activity heuristic.
  __tfa_prompt() { local __ec=$?; printf '\033]133;D;%s\007\033]133;A\007' "$__ec"; }
  case ";$PROMPT_COMMAND;" in
    *";__tfa_prompt;"*) ;;
    *) PROMPT_COMMAND="__tfa_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
fi
"""#
}
